#!/usr/bin/env crystal

# Generates the GB18030 4-byte range mapping tables by probing system iconv.
# For every BMP codepoint NOT in the GBK 2-byte range, we probe GB18030
# and record the 4-byte linear index.
# Output: src/charconv/tables/gb18030_ranges.cr

def iconv_convert(cd : LibC::IconvT, input : Bytes, output : Bytes) : Int32
  in_ptr = input.to_unsafe.as(LibC::Char*)
  in_left = LibC::SizeT.new(input.size)
  out_ptr = output.to_unsafe.as(LibC::Char*)
  out_left = LibC::SizeT.new(output.size)
  LibC.iconv(cd, Pointer(LibC::Char*).null, Pointer(LibC::SizeT).null,
             Pointer(LibC::Char*).null, Pointer(LibC::SizeT).null)
  result = LibC.iconv(cd, pointerof(in_ptr), pointerof(in_left), pointerof(out_ptr), pointerof(out_left))
  if result == ~LibC::SizeT.new(0) || in_left != 0
    -1
  else
    (output.size - out_left).to_i32
  end
end

def codepoint_to_utf8(cp : UInt32) : Bytes
  buf = IO::Memory.new(4)
  if cp < 0x80
    buf.write_byte(cp.to_u8)
  elsif cp < 0x800
    buf.write_byte((0xC0 | (cp >> 6)).to_u8)
    buf.write_byte((0x80 | (cp & 0x3F)).to_u8)
  elsif cp < 0x10000
    buf.write_byte((0xE0 | (cp >> 12)).to_u8)
    buf.write_byte((0x80 | ((cp >> 6) & 0x3F)).to_u8)
    buf.write_byte((0x80 | (cp & 0x3F)).to_u8)
  else
    buf.write_byte((0xF0 | (cp >> 18)).to_u8)
    buf.write_byte((0x80 | ((cp >> 12) & 0x3F)).to_u8)
    buf.write_byte((0x80 | ((cp >> 6) & 0x3F)).to_u8)
    buf.write_byte((0x80 | (cp & 0x3F)).to_u8)
  end
  buf.to_slice
end

cd_encode = LibC.iconv_open("GB18030", "UTF-8")
if cd_encode.address == ~LibC::SizeT.new(0)
  STDERR.puts "Failed to open iconv for GB18030"
  exit 1
end

cd_decode = LibC.iconv_open("UTF-32LE", "GB18030")
if cd_decode.address == ~LibC::SizeT.new(0)
  STDERR.puts "Failed to open iconv for GB18030 decode"
  exit 1
end

# Phase 1: Build map of codepoint → GB18030 linear index for 4-byte mappings
# We probe all BMP codepoints (0x0080..0xFFFF, skip surrogates)
puts "Probing GB18030 encode for BMP codepoints..."

# Map: unicode_codepoint → gb18030_linear_index (only for 4-byte forms)
four_byte_map = [] of {Int32, Int32}  # {unicode_cp, linear_index}

output = Bytes.new(8)
(0x0080..0xFFFF).each do |cp_i|
  cp = cp_i.to_u32
  next if cp >= 0xD800 && cp <= 0xDFFF

  utf8 = codepoint_to_utf8(cp)
  written = iconv_convert(cd_encode, utf8, output)

  next unless written == 4  # only interested in 4-byte forms

  b1 = output[0].to_i32
  b2 = output[1].to_i32
  b3 = output[2].to_i32
  b4 = output[3].to_i32

  # Validate 4-byte form
  next unless b1 >= 0x81 && b1 <= 0xFE
  next unless b2 >= 0x30 && b2 <= 0x39
  next unless b3 >= 0x81 && b3 <= 0xFE
  next unless b4 >= 0x30 && b4 <= 0x39

  linear = ((b1 - 0x81) * 10 + (b2 - 0x30)) * 126 * 10 + (b3 - 0x81) * 10 + (b4 - 0x30)
  four_byte_map << {cp_i, linear}
end

puts "Found #{four_byte_map.size} BMP codepoints with 4-byte GB18030 encoding"

# Sort by linear index
four_byte_map.sort_by! { |_, linear| linear }

# Phase 2: Compress into contiguous ranges
# Each range: {linear_start, unicode_start, count}
ranges = [] of {Int32, Int32, Int32}

i = 0
while i < four_byte_map.size
  unicode_start = four_byte_map[i][0]
  linear_start = four_byte_map[i][1]
  count = 1

  while i + count < four_byte_map.size
    next_unicode = four_byte_map[i + count][0]
    next_linear = four_byte_map[i + count][1]

    # Check if both unicode and linear are contiguous
    if next_linear == linear_start + count && next_unicode == unicode_start + count
      count += 1
    else
      break
    end
  end

  ranges << {linear_start, unicode_start, count}
  i += count
end

puts "Compressed to #{ranges.size} contiguous ranges"

# Phase 3: Also probe the decode direction for 4-byte sequences to verify
# and find the supplementary plane offset
puts "Probing supplementary plane..."

# Test a few supplementary codepoints
supp_start_linear = -1
(0x10000..0x10005).each do |cp_i|
  cp = cp_i.to_u32
  utf8 = codepoint_to_utf8(cp)
  written = iconv_convert(cd_encode, utf8, output)
  if written == 4
    b1 = output[0].to_i32
    b2 = output[1].to_i32
    b3 = output[2].to_i32
    b4 = output[3].to_i32
    linear = ((b1 - 0x81) * 10 + (b2 - 0x30)) * 126 * 10 + (b3 - 0x81) * 10 + (b4 - 0x30)
    if cp_i == 0x10000
      supp_start_linear = linear
      puts "U+10000 → linear #{linear}"
    end
  end
end

LibC.iconv_close(cd_encode)
LibC.iconv_close(cd_decode)

# Phase 4: Output Crystal source
io = IO::Memory.new
io.puts "# AUTO-GENERATED by tools/generate_gb18030_ranges.cr — DO NOT EDIT"
io.puts "# Generated from system iconv"
io.puts "#"
io.puts "# GB18030 4-byte range table: maps between linear index and Unicode codepoint"
io.puts "# for BMP characters not in GBK 2-byte form."
io.puts "# Each entry: {linear_start, unicode_start, count}"
io.puts "# Supplementary plane starts at linear index #{supp_start_linear}"
io.puts ""
io.puts "module CharConv::Tables::GB18030Ranges"
io.puts "  SUPP_START_LINEAR = #{supp_start_linear}"
io.puts ""
io.puts "  # {linear_start, unicode_start, count}"
io.puts "  BMP_RANGES = ["
ranges.each_with_index do |range, i|
  io.print "    {#{range[0]}, #{range[1]}, #{range[2]}},"
  io.print "  # U+#{range[1].to_s(16).upcase.rjust(4, '0')}..U+#{(range[1] + range[2] - 1).to_s(16).upcase.rjust(4, '0')}" if range[2] <= 20
  io.puts
end
io.puts "  ]"
io.puts "end"

output_path = File.join(__DIR__, "..", "src", "charconv", "tables", "gb18030_ranges.cr")
File.write(output_path, io.to_s)

puts "Written: #{output_path}"
puts "#{ranges.size} ranges, #{four_byte_map.size} total 4-byte mappings"
